// This file is auto-generated by @hey-api/openapi-ts

import type { RouteHandler } from 'fastify';

import type { CoursesCreateData, CoursesCreateResponses, CoursesDeleteData, CoursesDeleteResponses, CoursesIndexData, CoursesIndexResponses, CoursesShowData, CoursesShowResponses, LessonsCreateData, LessonsCreateResponses, LessonsDeleteData, LessonsDeleteResponses, LessonsIndexData, LessonsIndexResponses, LessonsShowData, LessonsShowResponses, TokensCreateData, TokensCreateErrors, TokensCreateResponses, UsersCreateData, UsersCreateErrors, UsersCreateResponses, UsersDeleteData, UsersDeleteErrors, UsersDeleteResponses, UsersIndexData, UsersIndexErrors, UsersIndexResponses, UsersShowData, UsersShowErrors, UsersShowResponses, UsersUpdateData, UsersUpdateErrors, UsersUpdateResponses } from './types.gen.js';

export type RouteHandlers = {
    coursesIndex: RouteHandler<{
        Querystring?: CoursesIndexData['query'];
        Reply: CoursesIndexResponses;
    }>;
    coursesCreate: RouteHandler<{
        Body: CoursesCreateData['body'];
        Reply: CoursesCreateResponses;
    }>;
    coursesDelete: RouteHandler<{
        Params: CoursesDeleteData['path'];
        Reply: CoursesDeleteResponses;
    }>;
    coursesShow: RouteHandler<{
        Params: CoursesShowData['path'];
        Reply: CoursesShowResponses;
    }>;
    lessonsIndex: RouteHandler<{
        Querystring?: LessonsIndexData['query'];
        Reply: LessonsIndexResponses;
    }>;
    lessonsCreate: RouteHandler<{
        Body: LessonsCreateData['body'];
        Reply: LessonsCreateResponses;
    }>;
    lessonsDelete: RouteHandler<{
        Params: LessonsDeleteData['path'];
        Reply: LessonsDeleteResponses;
    }>;
    lessonsShow: RouteHandler<{
        Params: LessonsShowData['path'];
        Reply: LessonsShowResponses;
    }>;
    tokensCreate: RouteHandler<{
        Body: TokensCreateData['body'];
        Reply: TokensCreateErrors & TokensCreateResponses;
    }>;
    usersIndex: RouteHandler<{
        Querystring?: UsersIndexData['query'];
        Reply: UsersIndexErrors & UsersIndexResponses;
    }>;
    usersCreate: RouteHandler<{
        Body: UsersCreateData['body'];
        Reply: UsersCreateErrors & UsersCreateResponses;
    }>;
    usersDelete: RouteHandler<{
        Params: UsersDeleteData['path'];
        Reply: UsersDeleteErrors & UsersDeleteResponses;
    }>;
    usersShow: RouteHandler<{
        Params: UsersShowData['path'];
        Reply: UsersShowErrors & UsersShowResponses;
    }>;
    usersUpdate: RouteHandler<{
        Body: UsersUpdateData['body'];
        Params: UsersUpdateData['path'];
        Reply: UsersUpdateErrors & UsersUpdateResponses;
    }>;
};
