// This file is auto-generated by @hey-api/openapi-ts

import type { RouteHandler } from 'fastify';

import type { CoursesCreateData, CoursesCreateErrors, CoursesCreateResponses, CoursesDeleteData, CoursesDeleteErrors, CoursesDeleteResponses, CoursesIndexData, CoursesIndexErrors, CoursesIndexResponses, CoursesLessonsCreateData, CoursesLessonsCreateErrors, CoursesLessonsCreateResponses, CoursesLessonsDeleteData, CoursesLessonsDeleteErrors, CoursesLessonsDeleteResponses, CoursesLessonsIndexData, CoursesLessonsIndexErrors, CoursesLessonsIndexResponses, CoursesLessonsShowData, CoursesLessonsShowErrors, CoursesLessonsShowResponses, CoursesShowData, CoursesShowErrors, CoursesShowResponses, CourseUpdateData, CourseUpdateErrors, CourseUpdateResponses, TokensCreateData, TokensCreateErrors, TokensCreateResponses, UsersCreateData, UsersCreateErrors, UsersCreateResponses, UsersDeleteData, UsersDeleteErrors, UsersDeleteResponses, UsersIndexData, UsersIndexErrors, UsersIndexResponses, UsersShowData, UsersShowErrors, UsersShowResponses, UsersUpdateData, UsersUpdateErrors, UsersUpdateResponses } from './types.gen.js';

export type RouteHandlers = {
    coursesIndex: RouteHandler<{
        Querystring?: CoursesIndexData['query'];
        Reply: CoursesIndexErrors & CoursesIndexResponses;
    }>;
    coursesCreate: RouteHandler<{
        Body: CoursesCreateData['body'];
        Reply: CoursesCreateErrors & CoursesCreateResponses;
    }>;
    coursesLessonsIndex: RouteHandler<{
        Params: CoursesLessonsIndexData['path'];
        Querystring?: CoursesLessonsIndexData['query'];
        Reply: CoursesLessonsIndexErrors & CoursesLessonsIndexResponses;
    }>;
    coursesLessonsCreate: RouteHandler<{
        Body: CoursesLessonsCreateData['body'];
        Params: CoursesLessonsCreateData['path'];
        Reply: CoursesLessonsCreateErrors & CoursesLessonsCreateResponses;
    }>;
    coursesLessonsDelete: RouteHandler<{
        Params: CoursesLessonsDeleteData['path'];
        Reply: CoursesLessonsDeleteErrors & CoursesLessonsDeleteResponses;
    }>;
    coursesLessonsShow: RouteHandler<{
        Params: CoursesLessonsShowData['path'];
        Reply: CoursesLessonsShowErrors & CoursesLessonsShowResponses;
    }>;
    coursesDelete: RouteHandler<{
        Params: CoursesDeleteData['path'];
        Reply: CoursesDeleteErrors & CoursesDeleteResponses;
    }>;
    coursesShow: RouteHandler<{
        Params: CoursesShowData['path'];
        Reply: CoursesShowErrors & CoursesShowResponses;
    }>;
    courseUpdate: RouteHandler<{
        Body: CourseUpdateData['body'];
        Params: CourseUpdateData['path'];
        Reply: CourseUpdateErrors & CourseUpdateResponses;
    }>;
    tokensCreate: RouteHandler<{
        Body: TokensCreateData['body'];
        Reply: TokensCreateErrors & TokensCreateResponses;
    }>;
    usersIndex: RouteHandler<{
        Querystring?: UsersIndexData['query'];
        Reply: UsersIndexErrors & UsersIndexResponses;
    }>;
    usersCreate: RouteHandler<{
        Body: UsersCreateData['body'];
        Reply: UsersCreateErrors & UsersCreateResponses;
    }>;
    usersDelete: RouteHandler<{
        Params: UsersDeleteData['path'];
        Reply: UsersDeleteErrors & UsersDeleteResponses;
    }>;
    usersShow: RouteHandler<{
        Params: UsersShowData['path'];
        Reply: UsersShowErrors & UsersShowResponses;
    }>;
    usersUpdate: RouteHandler<{
        Body: UsersUpdateData['body'];
        Params: UsersUpdateData['path'];
        Reply: UsersUpdateErrors & UsersUpdateResponses;
    }>;
};
