// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Course = {
    id: number;
    name: string;
    description: string;
    createdAt: string;
};

export type CourseCreate = {
    name: string;
    description: string;
};

export type CourseEditDto = {
    name?: string;
    description?: string;
};

export type Credentials = {
    email: string;
    password: string;
};

export type ForbiddenError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
};

export type Lesson = {
    id: number;
    name: string;
    courseId: number;
    body: string;
    createdAt: string;
};

export type LessonCreate = {
    name: string;
    courseId: number;
    body: string;
};

export type NotFoundError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
};

export type ProblemDetails = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
};

export type Token = {
    token: string;
};

export type UnauthorizedError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
};

export type UnprocessableEntityError = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    errors: Array<{
        message: string;
        rule: string;
        field: string;
    }>;
};

export type User = {
    id: number;
    fullName: string | null;
    email: string;
    updatedAt: string | null;
    createdAt: string;
};

export type UserCreateDto = {
    fullName: string | null;
    email: string;
    password: string;
};

export type UserEditDto = {
    fullName?: string | null;
    email?: string;
    password?: string;
};

export type CoursesIndexData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
    };
    url: '/courses';
};

export type CoursesIndexErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
};

export type CoursesIndexError = CoursesIndexErrors[keyof CoursesIndexErrors];

export type CoursesIndexResponses = {
    /**
     * The request has succeeded.
     */
    200: {
        data: Array<Course>;
    };
};

export type CoursesIndexResponse = CoursesIndexResponses[keyof CoursesIndexResponses];

export type CoursesCreateData = {
    body: CourseCreate;
    path?: never;
    query?: never;
    url: '/courses';
};

export type CoursesCreateErrors = {
    /**
     * Client error
     */
    422: UnprocessableEntityError;
};

export type CoursesCreateError = CoursesCreateErrors[keyof CoursesCreateErrors];

export type CoursesCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: Course;
};

export type CoursesCreateResponse = CoursesCreateResponses[keyof CoursesCreateResponses];

export type CoursesDeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/courses/{id}';
};

export type CoursesDeleteErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
    /**
     * Access is forbidden.
     */
    403: ForbiddenError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type CoursesDeleteError = CoursesDeleteErrors[keyof CoursesDeleteErrors];

export type CoursesDeleteResponses = {
    /**
     * There is no content to send for this request, but the headers may be useful.
     */
    204: void;
};

export type CoursesDeleteResponse = CoursesDeleteResponses[keyof CoursesDeleteResponses];

export type CoursesShowData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/courses/{id}';
};

export type CoursesShowErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type CoursesShowError = CoursesShowErrors[keyof CoursesShowErrors];

export type CoursesShowResponses = {
    /**
     * The request has succeeded.
     */
    200: Course;
};

export type CoursesShowResponse = CoursesShowResponses[keyof CoursesShowResponses];

export type CourseUpdateData = {
    body: CourseEditDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/courses/{id}';
};

export type CourseUpdateErrors = {
    /**
     * Access is forbidden.
     */
    403: ForbiddenError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type CourseUpdateError = CourseUpdateErrors[keyof CourseUpdateErrors];

export type CourseUpdateResponses = {
    /**
     * The request has succeeded.
     */
    200: Course;
};

export type CourseUpdateResponse = CourseUpdateResponses[keyof CourseUpdateResponses];

export type LessonsIndexData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
    };
    url: '/lessons';
};

export type LessonsIndexErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
};

export type LessonsIndexError = LessonsIndexErrors[keyof LessonsIndexErrors];

export type LessonsIndexResponses = {
    /**
     * The request has succeeded.
     */
    200: {
        data: Array<Lesson>;
    };
};

export type LessonsIndexResponse = LessonsIndexResponses[keyof LessonsIndexResponses];

export type LessonsCreateData = {
    body: LessonCreate;
    path?: never;
    query?: never;
    url: '/lessons';
};

export type LessonsCreateErrors = {
    /**
     * Client error
     */
    422: UnprocessableEntityError;
};

export type LessonsCreateError = LessonsCreateErrors[keyof LessonsCreateErrors];

export type LessonsCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: Lesson;
};

export type LessonsCreateResponse = LessonsCreateResponses[keyof LessonsCreateResponses];

export type LessonsDeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/lessons/{id}';
};

export type LessonsDeleteErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type LessonsDeleteError = LessonsDeleteErrors[keyof LessonsDeleteErrors];

export type LessonsDeleteResponses = {
    /**
     * There is no content to send for this request, but the headers may be useful.
     */
    204: void;
};

export type LessonsDeleteResponse = LessonsDeleteResponses[keyof LessonsDeleteResponses];

export type LessonsShowData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/lessons/{id}';
};

export type LessonsShowErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type LessonsShowError = LessonsShowErrors[keyof LessonsShowErrors];

export type LessonsShowResponses = {
    /**
     * The request has succeeded.
     */
    200: Lesson;
};

export type LessonsShowResponse = LessonsShowResponses[keyof LessonsShowResponses];

export type TokensCreateData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/tokens';
};

export type TokensCreateErrors = {
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type TokensCreateError = TokensCreateErrors[keyof TokensCreateErrors];

export type TokensCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: Token;
};

export type TokensCreateResponse = TokensCreateResponses[keyof TokensCreateResponses];

export type UsersIndexData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
    };
    url: '/users';
};

export type UsersIndexErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
};

export type UsersIndexError = UsersIndexErrors[keyof UsersIndexErrors];

export type UsersIndexResponses = {
    /**
     * The request has succeeded.
     */
    200: {
        data: Array<User>;
    };
};

export type UsersIndexResponse = UsersIndexResponses[keyof UsersIndexResponses];

export type UsersCreateData = {
    body: UserCreateDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersCreateErrors = {
    /**
     * Client error
     */
    422: UnprocessableEntityError;
};

export type UsersCreateError = UsersCreateErrors[keyof UsersCreateErrors];

export type UsersCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersDeleteErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type UsersDeleteError = UsersDeleteErrors[keyof UsersDeleteErrors];

export type UsersDeleteResponses = {
    /**
     * There is no content to send for this request, but the headers may be useful.
     */
    204: void;
};

export type UsersDeleteResponse = UsersDeleteResponses[keyof UsersDeleteResponses];

export type UsersShowData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersShowErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
};

export type UsersShowError = UsersShowErrors[keyof UsersShowErrors];

export type UsersShowResponses = {
    /**
     * The request has succeeded.
     */
    200: User;
};

export type UsersShowResponse = UsersShowResponses[keyof UsersShowResponses];

export type UsersUpdateData = {
    body: UserEditDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersUpdateErrors = {
    /**
     * Access is unauthorized.
     */
    401: UnauthorizedError;
    /**
     * The server cannot find the requested resource.
     */
    404: NotFoundError;
    /**
     * Client error
     */
    422: UnprocessableEntityError;
};

export type UsersUpdateError = UsersUpdateErrors[keyof UsersUpdateErrors];

export type UsersUpdateResponses = {
    /**
     * The request has succeeded.
     */
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];
