// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCourse = z.object({
    id: z.number(),
    name: z.string(),
    description: z.string(),
    createdAt: z.string()
});

export const zCourseCreate = z.object({
    name: z.string(),
    description: z.string()
});

export const zCredentials = z.object({
    email: z.string(),
    password: z.string()
});

export const zLesson = z.object({
    id: z.number(),
    name: z.string(),
    courseId: z.number(),
    body: z.string(),
    createdAt: z.string()
});

export const zLessonCreate = z.object({
    name: z.string(),
    courseId: z.number(),
    body: z.string()
});

export const zToken = z.object({
    token: z.string()
});

export const zUser = z.object({
    id: z.number(),
    fullName: z.string().nullable(),
    email: z.string(),
    updatedAt: z.string().nullable(),
    createdAt: z.string()
});

export const zUserCreateDto = z.object({
    fullName: z.string().nullable(),
    email: z.string(),
    password: z.string()
});

export const zCoursesIndexQuery = z.object({
    page: z.number().optional().default(1)
});

/**
 * The request has succeeded.
 */
export const zCoursesIndexResponse = z.object({
    data: z.array(zCourse)
});

export const zCoursesCreateBody = zCourseCreate;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zCoursesCreateResponse = zCourse;

export const zCoursesDeletePath = z.object({
    id: z.number()
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zCoursesDeleteResponse = z.void();

export const zCoursesShowPath = z.object({
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zCoursesShowResponse = zCourse;

export const zLessonsIndexQuery = z.object({
    page: z.number().optional().default(1)
});

/**
 * The request has succeeded.
 */
export const zLessonsIndexResponse = z.object({
    data: z.array(zLesson)
});

export const zLessonsCreateBody = zLessonCreate;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zLessonsCreateResponse = zLesson;

export const zLessonsDeletePath = z.object({
    id: z.number()
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zLessonsDeleteResponse = z.void();

export const zLessonsShowPath = z.object({
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zLessonsShowResponse = zLesson;

export const zTokensCreateBody = zCredentials;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zTokensCreateResponse = zToken;

export const zUsersIndexQuery = z.object({
    page: z.number().optional().default(1)
});

/**
 * The request has succeeded.
 */
export const zUsersIndexResponse = z.object({
    data: z.array(zUser)
});

export const zUsersCreateBody = zUserCreateDto;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zUsersCreateResponse = zUser;

export const zUsersDeletePath = z.object({
    id: z.number()
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zUsersDeleteResponse = z.void();

export const zUsersShowPath = z.object({
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zUsersShowResponse = zUser;
