// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCourse = z.object({
    id: z.number(),
    name: z.string(),
    description: z.string(),
    createdAt: z.string()
});

export const zCourseCreate = z.object({
    name: z.string(),
    description: z.string()
});

export const zCourseEditDto = z.object({
    name: z.string().optional(),
    description: z.string().optional()
});

export const zCredentials = z.object({
    email: z.string(),
    password: z.string()
});

export const zForbiddenError = z.object({
    type: z.string().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().optional()
});

export const zLesson = z.object({
    id: z.number(),
    name: z.string(),
    courseId: z.number(),
    body: z.string(),
    createdAt: z.string()
});

export const zLessonCreate = z.object({
    name: z.string(),
    body: z.string()
});

export const zNotFoundError = z.object({
    type: z.string().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().optional()
});

export const zPageMeta = z.object({
    page: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    perPage: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    total: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }),
    totalPages: z.number().int().min(-2147483648, { message: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zProblemDetails = z.object({
    type: z.string().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().optional()
});

export const zToken = z.object({
    token: z.string()
});

export const zUnauthorizedError = z.object({
    type: z.string().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().optional()
});

export const zUnprocessableEntityError = z.object({
    type: z.string().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().optional(),
    errors: z.array(z.object({
        message: z.string(),
        rule: z.string(),
        field: z.string()
    }))
});

export const zUser = z.object({
    id: z.number(),
    fullName: z.string().nullable(),
    email: z.string(),
    updatedAt: z.string().nullable(),
    createdAt: z.string()
});

export const zUserCreateDto = z.object({
    fullName: z.string().nullable(),
    email: z.string(),
    password: z.string()
});

export const zUserEditDto = z.object({
    fullName: z.string().nullish(),
    email: z.string().optional(),
    password: z.string().optional()
});

export const zCoursesIndexQuery = z.object({
    page: z.number().int().gte(1).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(1),
    perPage: z.number().int().gte(1).lte(100).optional().default(10)
});

/**
 * The request has succeeded.
 */
export const zCoursesIndexResponse = z.object({
    data: z.array(zCourse),
    meta: zPageMeta
});

export const zCoursesCreateBody = zCourseCreate;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zCoursesCreateResponse = zCourse;

export const zCoursesLessonsIndexPath = z.object({
    courseId: z.number()
});

export const zCoursesLessonsIndexQuery = z.object({
    page: z.number().int().gte(1).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(1),
    perPage: z.number().int().gte(1).lte(100).optional().default(10)
});

/**
 * The request has succeeded.
 */
export const zCoursesLessonsIndexResponse = z.object({
    data: z.array(zLesson),
    meta: zPageMeta
});

export const zCoursesLessonsCreateBody = zLessonCreate;

export const zCoursesLessonsCreatePath = z.object({
    courseId: z.number()
});

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zCoursesLessonsCreateResponse = zLesson;

export const zCoursesLessonsDeletePath = z.object({
    courseId: z.number(),
    id: z.number()
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zCoursesLessonsDeleteResponse = z.void();

export const zCoursesLessonsShowPath = z.object({
    courseId: z.number(),
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zCoursesLessonsShowResponse = zLesson;

export const zCoursesDeletePath = z.object({
    id: z.number()
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zCoursesDeleteResponse = z.void();

export const zCoursesShowPath = z.object({
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zCoursesShowResponse = zCourse;

export const zCourseUpdateBody = zCourseEditDto;

export const zCourseUpdatePath = z.object({
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zCourseUpdateResponse = zCourse;

export const zTokensCreateBody = zCredentials;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zTokensCreateResponse = zToken;

export const zUsersIndexQuery = z.object({
    page: z.number().int().gte(1).max(2147483647, { message: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(1),
    perPage: z.number().int().gte(1).lte(100).optional().default(10)
});

/**
 * The request has succeeded.
 */
export const zUsersIndexResponse = z.object({
    data: z.array(zUser),
    meta: zPageMeta
});

export const zUsersCreateBody = zUserCreateDto;

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export const zUsersCreateResponse = zUser;

export const zUsersDeletePath = z.object({
    id: z.number()
});

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export const zUsersDeleteResponse = z.void();

export const zUsersShowPath = z.object({
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zUsersShowResponse = zUser;

export const zUsersUpdateBody = zUserEditDto;

export const zUsersUpdatePath = z.object({
    id: z.number()
});

/**
 * The request has succeeded.
 */
export const zUsersUpdateResponse = zUser;
